<a href="https://colab.research.google.com/github/alifarah94/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Copy_of_LS_DS_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [41]:
##### Begin Working Here #####

!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-10-01 21:24:42--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.1’

LoanStats_2018Q4.cs     [                 <=>]  21.62M   884KB/s    in 25s

2019-10-01 21:25:08 (874 KB/s) - ‘LoanStats_2018Q4.csv.zip.1’ saved [22667400]

In [3]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [42]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","20000","20000","20000"," 36 months"," 14.47%","688.13","C","C2","bus driver","4 years","OWN","52000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","681xx","NE","30.65","1","Jun-1979","2","15","","6","0","15048","73%","22","w","15777.74","15777.74","6104.74","6104.74","4222.26","1882.48","0.0","0.0","0.0","Sep-2019","688.13","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","33157","0","2","1","1","8","18109","44","1","2","8628","73","20700","1","1","4","3","5526","5175","73","0","0","141","474","10","8","0","10","15","1","15","0","4","4","11","12","8","4","14","4","6","","0","0","2","95","50","0","0","61699","33157","20700","40999","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","25000","25000","25000"," 60 months"," 16.14%","609.82","C","C4","Production Manager","5 years","MORTGAGE","45000","Not Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","703xx","LA","37.09","0","Sep-2003","0","","","7","0","8901","36.8%","21","w","0.00","0.00","26653.1675796436","26653.17","25000.00","1653.17","0.0","0.0","0.0","Apr-2019","24857.33","","May-2019","0","","1","Individual","","","","0","1303","49524","0","2","1","2","7","40623","82","0","0","7830","67","24200","2","0","1","2","7075","10465","43.7","0","0","161","162","45","7","4","96","","7","","0","2","3","3","5","7","5","10","3","7","0","0","0","1","100","33.3","0","0","73683","49524","18600","49483","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","26500","26500","26500"," 60 months"," 11.31%","580.28","B","B3","Compliance Director","10+ years","MORTGAGE","134000","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","747xx","OK","18.91","0","Dec-2006","2","","","17","0","43640","65.4%","37","w","23410.70","23410.70","5197.54","5197.54","3089.30","2108.24","0.0","0.0","0.0","Sep-2019","580.28","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","381100","3","3","2","2","4","64335","46","1","3","10115","58","66700","2","1","7","6","22418","14577","70.4","0","0","114","144","3","3","4","22","","2","","0","8","10","9","10","7","13","26","10","17","0","0","0","4","100","66.7","0","0","430403","107975","49300","88875","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10400","10400","10400"," 36 months"," 12.98%","350.32","B","B5","Program Support Assistant ","10+ years","MORTGAGE","56099","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","800xx","CO","20.92","0","Jul-2013","2","32","67","8","1","1669","9.8%","10","w","8164.57","8164.57","3141.63","3141.63","2235.43","906.20","0.0","0.0","0.0","Sep-2019","350.32","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","39564","4","2","1","2","1","37895","92","3","6","725","36","17000","1","0","4","8","4946","15331","9.8","0","0","65","57","1","1","0","1","","0","32","0","3","3","6","6","3","6","7","3","8","0","0","0","4","90","0","1","0","60709","39564","17000","43709","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","35000","35000","35000"," 60 months"," 12.98%","796","B","B5","Sr. Vice President -Risk Manager","7 years","MORTGAGE","211646","Source Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","797xx","TX","15.09","0","Sep-1985","0","77","","13","0","55944","74.9%","39","w","0.00","0.00","36266.741551619","36266.74","35000.00","1266.74","0.0","0.0","0.0","Apr-2019","34712.6","","Sep-2019","0","","1","Joint App","272421","15.89","Source Verified","0","0","420931","1","3","1","2","5","26570","51","0","2","24795","65","74700","1","6","1","4","32379","8677","85.5","0","0","152","399","21","5","6","21","77","12","77","0","6","8","6","11","14","9","19","8","13","0","0","0","1","97.4","66.7","0","0","516204","82514","59700","51904","88364","Sep-1985","0","6","19","53.4","2","29","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","20000","20000","20000"," 36 months","  7.56%","622.68","A","A3","Teacher","10+ years","MORTGAGE","100000","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","982xx","WA","18.92","0","Feb-1999","0","48","","9","0","25416","29.9%","19","w","0.00","0.00","20215.79243","20215.79","20000.00","215.79","0.0","0.0","0.0","Feb-2019","20228.39","","Feb-2019","0","","1","Joint App","190000","11.75","Not Verified","0","0","515779","1","2","0","1","13","46153","71","1","2","9759","39","85100","2","2","0","5","57309","59684","29.9","0","0","171","238","1","1","5","1","","13","48","0","5","5","5","6","5","5","9","5","9","0","0","0","1","94.7","20","0","0","622183","71569","85100","74833","43287","Aug-1998","0","3","10","29.7","2","7","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","13000","13000","13000"," 36 months"," 17.97%","469.79","D","D1","Help Tech Supervisor","10+ years","MORTGAGE","92360","Source Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","300xx","GA","27.44","0","Sep-2006","1","68","","18","0","32020","49.6%","30","w","10370.35","10370.35","4208.64","4208.64","2629.65","1578.99","0.0","0.0","0.0","Sep-2019","469.79","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","131919","1","2","1","3","4","17310","60","0","2","6116","53","64600","1","4","1","5","7760","7140","70.7","0","0","120","147","16","4","2","18","","4","70","0","5","12","6","7","6","15","22","12","18","0","0","0","1","90","66.7","0","0","190803","49330","24400","28861","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","12000","12000","12000"," 60 months"," 14.47%","282.16","C","C2","Assistant Athletic Director of Marketing","1 year","RENT","67000","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","231xx","VA","28.39","0","Aug-2009","1","","","9","0","10018","50.9%","34","w","0.00","0.00","13140.1266634624","13140.13","12000.00","1140.13","0.0","0.0","0.0","Sep-2019","11169.83","","Sep-2019","0","","1","Individual","","","","0","0","184578","1","4","2","3","5","174560","97","0","1","4615","87","19700","1","1","2","4","20509","9682","50.9","0","0","112","80","23","5","0","23","","5","","0","3","3","5","5","26","5","8","3","9","0","0","0","2","100","0","0","0","183897","184578","19700","164197","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [116]:
import pandas as pd

df = pd.read_csv('LoanStats_2018Q4.csv',header=1, skipfooter=2) # the first row becomes header and removes the last 2 rows
df # check change

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

        id  member_id  ...  settlement_percentage  settlement_term
0      NaN        NaN  ...                    NaN              NaN
1      NaN        NaN  ...                    NaN              NaN
2      NaN        NaN  ...                    NaN              NaN
3      NaN        NaN  ...                    NaN              NaN
4      NaN        NaN  ...                    NaN              NaN
5      NaN        NaN  ...                    NaN              NaN
6      NaN        NaN  ...                    NaN              NaN
7      NaN        NaN  ...                    NaN              NaN
8      NaN        NaN  ...                    NaN              NaN
9      NaN        NaN  ...                    NaN              NaN
10     NaN        NaN  ...                    NaN              NaN
11     NaN        NaN  ...                    NaN              NaN
12     NaN        NaN  ...                    NaN              NaN
13     NaN        NaN  ...                    NaN              NaN
14     NaN        NaN  ...                    NaN              NaN
15     NaN        NaN  ...                    NaN              NaN
16     NaN        NaN  ...                    NaN              NaN
17     NaN        NaN  ...                    NaN              NaN
18     NaN        NaN  ...                    NaN              NaN
19     NaN        NaN  ...                    NaN              NaN
20     NaN        NaN  ...                    NaN              NaN
21     NaN        NaN  ...                    NaN              NaN
22     NaN        NaN  ...                    NaN              NaN
23     NaN        NaN  ...                    NaN              NaN
24     NaN        NaN  ...                    NaN              NaN
25     NaN        NaN  ...                    NaN              NaN
26     NaN        NaN  ...                    NaN              NaN
27     NaN        NaN  ...                    NaN              NaN
28     NaN        NaN  ...                    NaN              NaN
29     NaN        NaN  ...                    NaN              NaN
...     ..        ...  ...                    ...              ...
128382 NaN        NaN  ...                    NaN              NaN
128383 NaN        NaN  ...                    NaN              NaN
128384 NaN        NaN  ...                    NaN              NaN
128385 NaN        NaN  ...                    NaN              NaN
128386 NaN        NaN  ...                    NaN              NaN
128387 NaN        NaN  ...                    NaN              NaN
128388 NaN        NaN  ...                    NaN              NaN
128389 NaN        NaN  ...                    NaN              NaN
128390 NaN        NaN  ...                    NaN              NaN
128391 NaN        NaN  ...                    NaN              NaN
128392 NaN        NaN  ...                    NaN              NaN
128393 NaN        NaN  ...                    NaN              NaN
128394 NaN        NaN  ...                    NaN              NaN
128395 NaN        NaN  ...                    NaN              NaN
128396 NaN        NaN  ...                    NaN              NaN
128397 NaN        NaN  ...                    NaN              NaN
128398 NaN        NaN  ...                    NaN              NaN
128399 NaN        NaN  ...                    NaN              NaN
128400 NaN        NaN  ...                    NaN              NaN
128401 NaN        NaN  ...                    NaN              NaN
128402 NaN        NaN  ...                    NaN              NaN
128403 NaN        NaN  ...                    NaN              NaN
128404 NaN        NaN  ...                    NaN              NaN
128405 NaN        NaN  ...                    NaN              NaN
128406 NaN        NaN  ...                    NaN              NaN
128407 NaN        NaN  ...                    NaN              NaN
128408 NaN        NaN  ...                    NaN              NaN
128409 NaN        NaN  ...                    NaN              NaN
128410 NaN        NaN  ...                    NaN              NaN
128411 NaN        NaN  ...                    NaN              NaN

[128412 rows x 144 columns]

In [52]:
df.isnull().sum() # I was able to remove a lot of the null values from each column with skipfooter. I assume that the other columns with a lot null values have private data and data hasnt been given.

id                                            128412
member_id                                     128412
loan_amnt                                          0
funded_amnt                                        0
funded_amnt_inv                                    0
term                                               0
int_rate                                           0
installment                                        0
grade                                              0
sub_grade                                          0
emp_title                                      20947
emp_length                                     11704
home_ownership                                     0
annual_inc                                         0
verification_status                                0
issue_d                                            0
loan_status                                        0
pymnt_plan                                         0
url                                           128412
desc                                          128412
purpose                                            0
title                                              0
zip_code                                           0
addr_state                                         0
dti                                              237
delinq_2yrs                                        0
earliest_cr_line                                   0
inq_last_6mths                                     0
mths_since_last_delinq                         72196
mths_since_last_record                        112962
                                               ...
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
sec_app_revol_util                            111888
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
sec_app_collections_12_mths_ex_med            111630
sec_app_mths_since_last_major_derog           123258
hardship_flag                                      0
hardship_type                                 128343
hardship_reason                               128343
hardship_status                               128343
deferral_term                                 128343
hardship_amount                               128343
hardship_start_date                           128343
hardship_end_date                             128343
payment_plan_start_date                       128343
hardship_length                               128343
hardship_dpd                                  128343
hardship_loan_status                          128343
orig_projected_additional_accrued_interest    128345
hardship_payoff_balance_amount                128343
hardship_last_payment_amount                  128343
debt_settlement_flag                               0
debt_settlement_flag_date                     128244
settlement_status                             128244
settlement_date                               128244
settlement_amount                             128244
settlement_percentage                         128244
settlement_term                               128244
Length: 144, dtype: int64

In [0]:
# i had issues looping through the dataset due to google colab limited ram so only loops through the first 100 elements on the list. change the loop number when testing

def month_digit(x):
  new_list = []
  new_number = ""
  for i in range(1000):
    new_number = x[i].strip() # I looked through the data and noticed that every element in the column has 2 leading white spaces so I used the strip functing
    new_number = int(new_number[:2]) # then take the first 2 letters, turn it into an integer and then reasign it 
    new_list.append(new_number) #append it to list
  return new_list # and then return the list

In [123]:
df.term[:1000] = month_digit(df.term) # change index when testing. turns the first 1000 elements into an integer

AttributeError: ignored

In [156]:
df.term.value_counts() # check change. term now number

 36 months    87483
 60 months    39929
36              696
60              304
Name: term, dtype: int64

In [148]:
df['loan_status_is_great'] = 0

# a for loop to go through 1000 element. checks current or fully paid, adds a 1 to the column anything else adds 0 to the column  
# did not make a function due to time. takes very long to troubleshoot
for i in range(1000):
  if df['loan_status'][i] =="Current" or "Fully Paid":
    df['loan_status_is_great'][i] = 1
  else:
    df['loan_status_is_great'][i] = 0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

        id  member_id  ...  settlement_term  loan_status_is_great
0      NaN        NaN  ...              NaN                     1
1      NaN        NaN  ...              NaN                     1
2      NaN        NaN  ...              NaN                     1
3      NaN        NaN  ...              NaN                     1
4      NaN        NaN  ...              NaN                     1
5      NaN        NaN  ...              NaN                     1
6      NaN        NaN  ...              NaN                     1
7      NaN        NaN  ...              NaN                     1
8      NaN        NaN  ...              NaN                     1
9      NaN        NaN  ...              NaN                     1
10     NaN        NaN  ...              NaN                     1
11     NaN        NaN  ...              NaN                     1
12     NaN        NaN  ...              NaN                     1
13     NaN        NaN  ...              NaN                     1
14     NaN        NaN  ...              NaN                     1
15     NaN        NaN  ...              NaN                     1
16     NaN        NaN  ...              NaN                     1
17     NaN        NaN  ...              NaN                     1
18     NaN        NaN  ...              NaN                     1
19     NaN        NaN  ...              NaN                     1
20     NaN        NaN  ...              NaN                     1
21     NaN        NaN  ...              NaN                     1
22     NaN        NaN  ...              NaN                     1
23     NaN        NaN  ...              NaN                     1
24     NaN        NaN  ...              NaN                     1
25     NaN        NaN  ...              NaN                     1
26     NaN        NaN  ...              NaN                     1
27     NaN        NaN  ...              NaN                     1
28     NaN        NaN  ...              NaN                     1
29     NaN        NaN  ...              NaN                     1
...     ..        ...  ...              ...                   ...
128382 NaN        NaN  ...              NaN                     0
128383 NaN        NaN  ...              NaN                     0
128384 NaN        NaN  ...              NaN                     0
128385 NaN        NaN  ...              NaN                     0
128386 NaN        NaN  ...              NaN                     0
128387 NaN        NaN  ...              NaN                     0
128388 NaN        NaN  ...              NaN                     0
128389 NaN        NaN  ...              NaN                     0
128390 NaN        NaN  ...              NaN                     0
128391 NaN        NaN  ...              NaN                     0
128392 NaN        NaN  ...              NaN                     0
128393 NaN        NaN  ...              NaN                     0
128394 NaN        NaN  ...              NaN                     0
128395 NaN        NaN  ...              NaN                     0
128396 NaN        NaN  ...              NaN                     0
128397 NaN        NaN  ...              NaN                     0
128398 NaN        NaN  ...              NaN                     0
128399 NaN        NaN  ...              NaN                     0
128400 NaN        NaN  ...              NaN                     0
128401 NaN        NaN  ...              NaN                     0
128402 NaN        NaN  ...              NaN                     0
128403 NaN        NaN  ...              NaN                     0
128404 NaN        NaN  ...              NaN                     0
128405 NaN        NaN  ...              NaN                     0
128406 NaN        NaN  ...              NaN                     0
128407 NaN        NaN  ...              NaN                     0
128408 NaN        NaN  ...              NaN                     0
128409 NaN        NaN  ...              NaN                     0
128410 NaN        NaN  ...              NaN                     0
128411 NaN        NaN  ...              NaN                     0

[128412 rows x 145 columns]

In [149]:
df.head(100) #check change

    id  member_id  ...  settlement_term  loan_status_is_great
0  NaN        NaN  ...              NaN                     1
1  NaN        NaN  ...              NaN                     1
2  NaN        NaN  ...              NaN                     1
3  NaN        NaN  ...              NaN                     1
4  NaN        NaN  ...              NaN                     1
5  NaN        NaN  ...              NaN                     1
6  NaN        NaN  ...              NaN                     1
7  NaN        NaN  ...              NaN                     1
8  NaN        NaN  ...              NaN                     1
9  NaN        NaN  ...              NaN                     1
10 NaN        NaN  ...              NaN                     1
11 NaN        NaN  ...              NaN                     1
12 NaN        NaN  ...              NaN                     1
13 NaN        NaN  ...              NaN                     1
14 NaN        NaN  ...              NaN                     1
15 NaN        NaN  ...              NaN                     1
16 NaN        NaN  ...              NaN                     1
17 NaN        NaN  ...              NaN                     1
18 NaN        NaN  ...              NaN                     1
19 NaN        NaN  ...              NaN                     1
20 NaN        NaN  ...              NaN                     1
21 NaN        NaN  ...              NaN                     1
22 NaN        NaN  ...              NaN                     1
23 NaN        NaN  ...              NaN                     1
24 NaN        NaN  ...              NaN                     1
25 NaN        NaN  ...              NaN                     1
26 NaN        NaN  ...              NaN                     1
27 NaN        NaN  ...              NaN                     1
28 NaN        NaN  ...              NaN                     1
29 NaN        NaN  ...              NaN                     1
..  ..        ...  ...              ...                   ...
70 NaN        NaN  ...              NaN                     1
71 NaN        NaN  ...              NaN                     1
72 NaN        NaN  ...              NaN                     1
73 NaN        NaN  ...              NaN                     1
74 NaN        NaN  ...              NaN                     1
75 NaN        NaN  ...              NaN                     1
76 NaN        NaN  ...              NaN                     1
77 NaN        NaN  ...              NaN                     1
78 NaN        NaN  ...              NaN                     1
79 NaN        NaN  ...              NaN                     1
80 NaN        NaN  ...              NaN                     1
81 NaN        NaN  ...              NaN                     1
82 NaN        NaN  ...              NaN                     1
83 NaN        NaN  ...              NaN                     1
84 NaN        NaN  ...              NaN                     1
85 NaN        NaN  ...              NaN                     1
86 NaN        NaN  ...              NaN                     1
87 NaN        NaN  ...              NaN                     1
88 NaN        NaN  ...              NaN                     1
89 NaN        NaN  ...              NaN                     1
90 NaN        NaN  ...              NaN                     1
91 NaN        NaN  ...              NaN                     1
92 NaN        NaN  ...              NaN                     1
93 NaN        NaN  ...              NaN                     1
94 NaN        NaN  ...              NaN                     1
95 NaN        NaN  ...              NaN                     1
96 NaN        NaN  ...              NaN                     1
97 NaN        NaN  ...              NaN                     1
98 NaN        NaN  ...              NaN                     1
99 NaN        NaN  ...              NaN                     1

[100 rows x 145 columns]

In [0]:
df['last_pymnt_d_month'] = " "#, 'last_pymnt_d_year columns']
df['last_pymnt_d_year columns'] = " "

In [155]:
df.head()

   id  member_id  ...  last_pymnt_d_month  last_pymnt_d_year columns
0 NaN        NaN  ...
1 NaN        NaN  ...
2 NaN        NaN  ...
3 NaN        NaN  ...
4 NaN        NaN  ...

[5 rows x 147 columns]

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01